version: '3.5'

services:
  client:
    container_name: client
    hostname: client
    build:
      context: ./client/
    restart: "no"
    volumes:
      - ./data/:/data/
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server

  server:
    container_name: server
    hostname: server
    build:
      context: ./server/
    restart: "no"
    volumes:
      - ./data/:/data/
    ports:
      - "9000:9000"
